<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IAEngine.Memory.Local</RootNamespace>
    <AssemblyName>IAEngine.Memory.Local</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../IAEngine.Core/IAEngine.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
  </ItemGroup>
</Project>
